-- OncoChat SQLite schema: history, observability and answer cache.
-- Loaded by app/store/db.py at startup. Every statement is idempotent (IF NOT EXISTS), so it is safe to run
-- on an existing database. Timestamps are Unix epoch seconds (REAL). *_json columns hold JSON text.

-- One row per chat thread shown in the sidebar.
CREATE TABLE IF NOT EXISTS conversations (
    id          TEXT PRIMARY KEY,      -- uuid hex, generated by the API
    title       TEXT NOT NULL,         -- first question, truncated to 80 chars
    created_at  REAL NOT NULL
);

-- One row per question asked: the full trace of how it was answered.
CREATE TABLE IF NOT EXISTS requests (
    id                 TEXT PRIMARY KEY,                               -- request_id, also used by /api/traces/{id}
    conversation_id    TEXT NOT NULL REFERENCES conversations(id),
    question           TEXT NOT NULL,
    answer             TEXT,                                           -- prose shown to the user
    status             TEXT,          -- ok | cached | help | fallback (safe "I don't know") | error (LLM down)
    intent             TEXT,          -- help | greeting | data | other (rule-based router)
    lang               TEXT,          -- en | fr
    tier               TEXT,          -- fast | smart: final model tier used (NULL when no LLM was needed)
    model              TEXT,          -- e.g. qwen2.5:3b
    escalated          INTEGER DEFAULT 0,   -- 1 if the fast tier failed a guard and the smart tier retried
    cache_hit          INTEGER DEFAULT 0,   -- 1 if served from the cache table
    complexity_score   REAL,          -- model-selector score (threshold decides fast vs smart)
    features_json      TEXT,          -- selector features, e.g. {"comparison": 1, "extra_cancers": 2}
    guard_json         TEXT,          -- guard verdict: {"ok": bool, "reasons": [...], "tier": ...}
    tool_calls_json    TEXT,          -- [{"name", "args", "error"}] for every tool the LLM called
    data_json          TEXT,          -- tables rendered by the UI (built from tool results, not from the LLM)
    latency_ms         REAL,          -- end-to-end time inside the graph
    prompt_tokens      INTEGER,       -- summed over all LLM calls of the request
    completion_tokens  INTEGER,
    data_version       TEXT,          -- hash of the CSV: which data produced this answer
    prompt_version     TEXT,          -- PROMPT_VERSION: which prompts produced this answer
    error              TEXT,          -- LLM error message, if any
    created_at         REAL NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_requests_conv    ON requests(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_requests_created ON requests(created_at);

-- One row per graph node executed for a request (cache_lookup, router, agent, tools, guard...),
-- in execution order: the step-by-step timeline of "View trace".
CREATE TABLE IF NOT EXISTS steps (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    request_id   TEXT NOT NULL REFERENCES requests(id),
    seq          INTEGER NOT NULL,     -- 0, 1, 2... order of execution
    node         TEXT NOT NULL,        -- graph node name
    latency_ms   REAL,
    detail_json  TEXT                  -- node-specific detail (tool calls, guard reasons, chosen tier...)
);
CREATE INDEX IF NOT EXISTS idx_steps_req ON steps(request_id, seq);

-- Exact-match answer cache (never semantic: see app/store/cache.py).
CREATE TABLE IF NOT EXISTS cache (
    key           TEXT PRIMARY KEY,    -- sha256(normalized question | data_version | prompt_version | models)
    payload_json  TEXT NOT NULL,       -- {"answer", "data", "tier", "model", "intent", "lang"}
    created_at    REAL NOT NULL,
    expires_at    REAL NOT NULL,       -- created_at + CACHE_TTL_S
    hits          INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cache_expires ON cache(expires_at);

-- Purge cache whenever a new entry is written, so the invariant lives in the database whatever code writes to it.
CREATE TRIGGER IF NOT EXISTS trg_cache_purge_expired
AFTER INSERT ON cache
BEGIN
    DELETE FROM cache WHERE expires_at < NEW.created_at;
END;
